update-to-1.6.11

diff --git a/flutter-shared.sh.patch b/flutter-shared.sh.patch
--- a/flutter-shared.sh.patch
+++ b/flutter-shared.sh.patch
@@ -1,13 +1,13 @@
 diff --git a/flutter/bin/internal/shared.sh b/flutter/bin/internal/shared.sh
-index 2a47642b16..2a4d41a8b0 100644
+index f97a75d..bbb7870 100644
 --- a/flutter/bin/internal/shared.sh
 +++ b/flutter/bin/internal/shared.sh
-@@ -157,7 +157,7 @@ function upgrade_flutter () (
-       export PUB_SUMMARY_ONLY=1
-     fi
-     export PUB_ENVIRONMENT="$PUB_ENVIRONMENT:flutter_install"
--    pub_upgrade_with_retry
-+    #pub_upgrade_with_retry
- 
-     # Move the old snapshot - we can't just overwrite it as the VM might currently have it
-     # memory mapped (e.g. on flutter upgrade). For downloading a new dart sdk the folder is moved,
+@@ -20,7 +20,7 @@ function pub_upgrade_with_retry {
+   local total_tries="10"
+   local remaining_tries=$((total_tries - 1))
+   while [[ "$remaining_tries" -gt 0 ]]; do
+-    (cd "$FLUTTER_TOOLS_DIR" && "$DART" pub upgrade --suppress-analytics) && break
++    (cd "$FLUTTER_TOOLS_DIR" && "$DART" pub upgrade --offline --suppress-analytics) && break
+     >&2 echo "Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... ($remaining_tries tries left)"
+     remaining_tries=$((remaining_tries - 1))
+     sleep 5
